### ISSUE TITLE
Why can't it be installed? pip install xtgeo is OK. What should I do

### ISSUE THREAD

**Issue by clearxiaofeifei** [equinor/resdata#1026]
![Image](https://github.com/user-attachments/assets/a25862d8-d8e4-42ed-9db9-65ba63acb071)

**Comment by berland** [comment]
It looks like you are running in Windows. `resdata` is not distributed in a Windows version on Pypi, and it is not simple to compile on Windows. See e.g. https://github.com/equinor/resdata/issues/726

**Comment by eivindjahren** [comment]
Closing this as we it seems to have been solved by putting windows wheels on pypi.
