### ISSUE TITLE
Add package and subpackage documentation to all the __init__ files

### ISSUE THREAD

**Issue by joakim-hove** [equinor/resdata#527]
All the `__init__.py`files in the code base should get docstrings, so that e.g. `pydoc ecl` and `pydoc ecl.grid` will give a meaningfull overview documentation.

When this complete it should be backported to the 2.3 release version.

**Comment by dotfloat** [comment]
Here's a list of all of the `__init__.py` files that need docstrings:
- TODO

**Comment by pinkwah** [comment]
Closing as this is stale
