### ISSUE TITLE
Get rid of deprecation warnings

### ISSUE THREAD

**Issue by markusdregi** [equinor/resdata#537]
Successfully run tests on Jenkins with the _komodo_ environment and **no** deprecation warnings. This can be achieved by making all deprecation warnings errors.

Today there are quite a bit of deprecation warnings related to numpy usage internally. These should go away before we start deprecating parts of our own API..

**Comment by eivindjahren** [comment]
This seems to have been closed already, but deprecation warnings are a constant issue that will have to be tackled continously.
