### ISSUE TITLE
Roadmap - Ecl

### ISSUE THREAD

**Issue by markusdregi** [equinor/resdata#564]
**Current state of libecl**

The first and very important step towards making _libecl_ a library was made almost two years ago when the Ensembles/ert repository was split into libecl, libres and ert.  Unfortunately, the library still wears sign of initially being an integrated part of _ERT_.  There are specifically two issues we need to improve:

- the number of entry-points is an order of magnitude too high
- it is challenging to make computations directly on top of the data
 loaded by _libecl_, and hence the tendency has often been to increase
 the number of entry-points instead of having application specific
 logic actually be in the application or forward model.

**Goal**
The goal is to make a more efficient, extensible, and robust C(++)/Python library for reading _Eclipse_ files.  The consumer should specifically be able to utilize _libecl_ efficiently in their applications without changing the source code of _libecl_.

**Approach**
We will design an API for _libecl_ module by module that enables the consumer as described above.  For each incremental step we will swap the current implementation with the new (leaving the old API as is), at the same  time making the new API vailable to the users under an `ecl3` namespace.  In this manner, the two API's will utilize and test the same code base (which of course is
extremely valuable) and make the maintenance burden bearable.

**Effect on _libecl_ contributions**
During this period, changes to the already exposed symbols in _libecl_ will be rejected (except for extraordinary circumstances).  An extension of the current API may be accepted, mainly to facilitate our current consumers while the new API is developed.  It should however be noted that one will have to expect to later on move the application specific logic to the application itself.  If there is an existing API (old or new) that makes it feasible for the user to have application specific logic on the application side, that approach will be encouraged.

**Main version**
At some point in the future we will deprecate the current API and the new API will be considered the standard `ecl`.

**Comment by dotfloat** [comment]
We should schedule a meeting regarding this. If you could do it when you have time and brain capacity then it would be nice. Include @eivindjahren @lars-petter-hauge .

**Comment by markusdregi** [comment]
Sure can! How about one of you call for a meeting after Christmas to relaunch the discussion on the future of libecl? :)

**Comment by dotfloat** [comment]
I have time available between 4 Jan 2021 and 30 Dec 2022.

**Comment by pinkwah** [comment]
Closing due to staleness. The future of resdata should be revisited, but then we can create a new issue.
