### ISSUE TITLE
Incorrect summary vectors for restart cases that are not finished

### ISSUE THREAD

**Issue by eivindsm** [equinor/resdata#628]
Ref old issue #503. libecl summary can at times return misleading values for restart cases that have not finished properly. For a restart case the current code first reads vectors from original simulation, then overwrite with values found in the restart case. For instances where the restart case has crashed or is still running only part of the vector is overwritten and some of the values from original simulation shine through. This can be deceiving, as it gives the impression the simulation has finished and that the values are incorrect.

**Comment by dotfloat** [comment]
Is this still an issue?

**Comment by eivindsm** [comment]
I would strongly assume so, but have not reconfirmed. Is the issue possible to understand from my description?

**Comment by dotfloat** [comment]
Yeah I think I understand. We'll need to figure out how to prioritise this issue in a future planning.

**Comment by pinkwah** [comment]
Closing due to staleness.
