### ISSUE TITLE
FreeBSD fix for util_abort_gnu.c

### ISSUE THREAD

**Issue by edscott** [equinor/resdata#738]
attached fix:  
[util_abort_gnu.c.patch.txt](https://github.com/equinor/libecl/files/5395834/util_abort_gnu.c.patch.txt)

Show stopper in FreeBSD, clang 8.0.1:

[16%] Building C object lib/CMakeFiles/ecl.dir/util/util_abort_gnu.c.o
/usr/home/edscott/src/OPM/libecl/lib/util/util_abort_gnu.c:58:6: error: No known program_invocation_name in runtime library
    error No known program_invocation_name in runtime library
     ^
/usr/home/edscott/src/OPM/libecl/lib/util/util_abort_gnu.c:287:56: error: use of undeclared identifier 'PATH_MAX'
        char* program_invocation_name = (char*)alloca (PATH_MAX);
                                                       ^
2 errors generated.

**Comment by pinkwah** [comment]
Thanks for your contribution. I was intending to merge this three years ago, but right now there is no work being done on this project.

We currently don't support FreeBSD. To start supporting it there would need to be a Github Actions workflow that runs on every PR to ensure that we don't break compatibility. We may accept this if it were a PR, but we don't have capacity to support this.
