### ISSUE TITLE
Enable printing both c and python stacktrace

### ISSUE THREAD

**Issue by sondreso** [equinor/resdata#767]
@mortalisk commented on [Thu Dec 05 2019](https://github.com/equinor/scout/issues/101)

In order to print python stacktraces it should be sufficient to install the package faulthander (for python 2, while in python 3 it is included), and have the environment variable PYTHONFAULTHANDLER set, or call faulthandler.enable() somewhere before libecl is loaded. It should be possible to have both the c stack trace and python one print in this way. By setting environment variable ECL_SKIP_SIGNAL to YES, one can disable the c stack trace if desired.

The enabling code was introduced here:
equinor/libecl/pull/632
equinor/libecl/pull/634

---

@markusdregi commented on [Tue Aug 04 2020](https://github.com/equinor/scout/issues/101#issuecomment-668390271)

Is this issue still relevant @mortalisk?

---

@mortalisk commented on [Tue Aug 04 2020](https://github.com/equinor/scout/issues/101#issuecomment-668520162)

I'm not sure. It was about enabling this by default. But I suspect @dotfloat perhaps knows more about the status of util_abort currently.

---

@dotfloat commented on [Tue Aug 04 2020](https://github.com/equinor/scout/issues/101#issuecomment-668524004)

While it's not possible to have `util_abort` throw Python exceptions without rewriting all of the C code, it might be possible to emulate something similar via signals. `util_abort` is run:

1. Have C create a backtrace and place it in some global variable.
2. Raise some signal that isn't used for anything. (`SIGUSR1`?)
3. Have Python catch this signal.
4. Python uses `ctypes` to fetch the C backtrace.
5. Print Python backtrace.
6. `os.abort()`

I believe you can merge the backtraces so it'll look like one. Anyway, I think it might be wise to not close the issue just yet.

---

@mortalisk commented on [Tue Aug 04 2020](https://github.com/equinor/scout/issues/101#issuecomment-668584410)

Hmm. Well, we had a solution of simply letting C write it's stacktrace, before raising a signal which python then caught in it's faulthandler, which would also print the python stack trace. I just seem to remember you saw some bug in this, an infinite loop or something. But perhaps I'm mistaken. Anyway, have you changed anything recently that would make this approach not work? I can check if it works still.

---

@markusdregi commented on [Wed Aug 05 2020](https://github.com/equinor/scout/issues/101#issuecomment-668985374)

I'm keeping it open then

---

@mortalisk commented on [Wed Aug 05 2020](https://github.com/equinor/scout/issues/101#issuecomment-669167354)

I checked the behaviour now. If one enables python faulthanderl with env var PYTHONFAULTHANDLER I observe the following:

- On a call to util_abort, it prints first the c stack trace, then it prints the python stack trace
- On a sigsegv it only prints the python stack trace

If we were to install the python fault hander in code instead, and only make it listen for the abort signal, it would probably print both stack traces.

---

@mortalisk commented on [Wed Aug 05 2020](https://github.com/equinor/scout/issues/101#issuecomment-669185455)

By adding the following lines before 'updateAbortSignals( )'  in python/res/__init__.py:

    import faulthandler
    import signal

    signal.signal(signal.SIGUSR1, lambda a, b: exit(1))
    faulthandler.register(signal.SIGUSR1, chain=True)

and changing util_abort__ to raise SIGUSR1 in stead of SIGABRT, I managed to get both the C stacktrace and the python stack trace printed both on SIGSEGV and on a call to util_abort.

---

@mortalisk commented on [Fri Aug 07 2020](https://github.com/equinor/scout/issues/101#issuecomment-670371851)

I performed the changed I described. Are there people using libecl without libres? If so we probably need a way to selectively throw either SIGUSR1 or SIGABRT. But if not, then this should probably work fine, I guess.

---

@markusdregi commented on [Fri Aug 07 2020](https://github.com/equinor/scout/issues/101#issuecomment-670377772)

> Are there people using libecl without libres?

Yes! And we should either way design this way as it is kept as different projects ;)

**Comment by pinkwah** [comment]
Closing. We are not using `util_abort` much in other projects and this has been a very technically complicated issue to work on, so I don't think we'll revisit this ever.
