### ISSUE TITLE
Replace c tests with catch2 tests

### ISSUE THREAD

**Issue by eivindjahren** [equinor/resdata#768]
The old c tests are difficult to work with because they  use homebrew testing functionality such as `TestArea` and `test_assert_true` as well as internal test data. These tests should be rewritten to use [catch2](https://github.com/catchorg/Catch2) and synthetic test data.

The new tests should

* Generate their own data whenever possible
* Follow the setup described in https://github.com/catchorg/Catch2/blob/devel/docs/tutorial.md#scaling-up
* reside in `lib/tests`.
* Can use c++ functionality
* Replace testing of functionality already in an existing test.

The tests that need replacing are:
- [x] lib/ecl/tests/ecl_grid_case.cpp	
- [x] lib/ecl/tests/ecl_grid_simple.cpp
- [x] lib/ecl/tests/ecl_grid_DEPTHZ.cpp
- [x] lib/ecl/tests/ecl_alloc_cpgrid.cpp
- [x] lib/ecl/tests/ecl_alloc_grid_dxv_dyv_dzv.cpp
- [ ] lib/util/tests/ert_util_alloc_file_components.cpp
- [ ] lib/util/tests/ert_util_split_path.cpp
- [ ] lib/util/tests/ert_util_approx_equal.cpp
- [ ] lib/util/tests/ert_util_before_after.cpp
- [ ] lib/util/tests/ert_util_binary_split.cpp
- [ ] lib/util/tests/ert_util_buffer.cpp
- [ ] lib/util/tests/ert_util_clamp.cpp
- [ ] lib/util/tests/ert_util_chdir.cpp
- [ ] lib/util/tests/ert_util_filename.cpp
- [ ] lib/util/tests/ert_util_hash_test.cpp
- [ ] lib/util/tests/ert_util_parent_path.cpp
- [ ] lib/util/tests/ert_util_realpath.cpp
- [ ] lib/util/tests/ert_util_relpath_test.cpp
- [ ] lib/util/tests/ert_util_rng.cpp
- [ ] lib/util/tests/ert_util_sscan_test.cpp
- [ ] lib/util/tests/ert_util_statistics.cpp
- [ ] lib/util/tests/ert_util_strcat_test.cpp
- [ ] lib/util/tests/ert_util_stringlist_test.cpp
- [ ] lib/util/tests/ert_util_string_util.cpp
- [ ] lib/util/tests/ert_util_strstr_int_format.cpp
- [ ] lib/util/tests/ert_util_type_vector_functions.cpp
- [ ] lib/util/tests/ert_util_vector_test.cpp
- [ ] lib/util/tests/ert_util_datetime.cpp
- [ ] lib/util/tests/ert_util_normal_path.cpp
- [ ] lib/util/tests/ert_util_mkdir_p.cpp
- [ ] lib/util/tests/test_area.cpp
- [ ] lib/ecl/tests/ecl_fault_block_layer.cpp
- [ ] lib/ecl/tests/ecl_util_path_access.cpp
- [ ] lib/ecl/tests/ecl_grid_add_nnc.cpp
- [ ] lib/ecl/tests/ecl_grid_copy.cpp
- [ ] lib/ecl/tests/ecl_grid_create.cpp
- [x] lib/ecl/tests/ecl_grid_fwrite.cpp
- [ ] lib/ecl/tests/ecl_grid_unit_system.cpp
- [ ] lib/ecl/tests/ecl_grid_export.cpp
- [ ] lib/ecl/tests/ecl_grid_init_fwrite.cpp
- [ ] lib/ecl/tests/ecl_grid_reset_actnum.cpp
- [ ] lib/ecl/tests/ecl_grid_ext_actnum.cpp
- [ ] lib/ecl/tests/ecl_nnc_export_intersect.cpp
- [ ] lib/ecl/tests/ecl_sum_restart.cpp
- [ ] lib/ecl/tests/ecl_sum_data_intermediate_test.cpp
- [ ] lib/ecl/tests/ecl_grid_cell_contains.cpp
- [ ] lib/ecl/tests/ecl_unsmry_loader_test.cpp
- [ ] lib/ecl/tests/ecl_init_file.cpp
- [ ] lib/ecl/tests/ecl_kw_space_pad.cpp
- [ ] lib/ecl/tests/ecl_kw_cmp_string.cpp
- [ ] lib/ecl/tests/ecl_kw_equal.cpp
- [ ] lib/ecl/tests/ecl_kw_fread.cpp
- [ ] lib/ecl/tests/ecl_kw_grdecl.cpp
- [ ] lib/ecl/tests/ecl_kw_init.cpp
- [ ] lib/ecl/tests/ecl_nnc_geometry.cpp
- [ ] lib/ecl/tests/ecl_nnc_info_test.cpp
- [ ] lib/ecl/tests/ecl_nnc_vector.cpp
- [ ] lib/ecl/tests/ecl_rft_cell.cpp
- [ ] lib/ecl/tests/ecl_sum_alloc_resampled_test.cpp
- [ ] lib/ecl/tests/ecl_file_view.cpp
- [ ] lib/ecl/tests/test_ecl_file_index.cpp
- [ ] lib/ecl/tests/test_transactions.cpp
- [ ] lib/ecl/tests/ecl_rst_file.cpp
- [ ] lib/ecl/tests/ecl_sum_writer.cpp
- [ ] lib/ecl/tests/ecl_util_filenames.cpp
- [ ] lib/ecl/tests/ecl_util_make_date_no_shift.cpp
- [ ] lib/ecl/tests/ecl_util_make_date_shift.cpp
- [ ] lib/ecl/tests/ecl_util_month_range.cpp
- [ ] lib/ecl/tests/ecl_valid_basename.cpp
- [ ] lib/ecl/tests/test_ecl_nnc_data.cpp
- [ ] lib/ecl/tests/ecl_nnc_pair.cpp
- [ ] lib/ecl/tests/well_conn_collection.cpp
- [ ] lib/ecl/tests/well_branch_collection.cpp
- [ ] lib/ecl/tests/well_conn.cpp
- [ ] lib/ecl/tests/well_state.cpp
- [ ] lib/ecl/tests/well_segment.cpp
- [ ] lib/ecl/tests/well_segment_conn.cpp
- [ ] lib/ecl/tests/well_segment_collection.cpp
- [ ] lib/ecl/tests/ecl_file.cpp

**Comment by pinkwah** [comment]
We are not actively working on this project and would rather have it be replaced by a different library in the future. Closing.
