### ISSUE TITLE
Support base names of up 136 characters 

### ISSUE THREAD

**Issue by sondreso** [equinor/resdata#872]
Since version 2021.04 Eclipse now supports supports base case file names longer than 72 characters (up 136 characters).

From the [Eclipse changelog](https://statoilsrm.sharepoint.com/sites/PETECHUB/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FPETECHUB%2FShared%20Documents%2FReservoirModelingandSimulation%2FReservoir%20simulation%2FTools%2FSimulators%2FEclipse%2FReleaseNotes%2FEclipseReleaseNotes%5F2021%2E4%2Epdf&parent=%2Fsites%2FPETECHUB%2FShared%20Documents%2FReservoirModelingandSimulation%2FReservoir%20simulation%2FTools%2FSimulators%2FEclipse%2FReleaseNotes)

>  The RESTART record written to the SMSPEC file now supports base case file names longer than 72 characters. This allows base case results from long file names to be loaded in Petrel along with restart results.

And from the File Format Reference Manual:
![image](https://user-images.githubusercontent.com/3437958/184120523-fe62d6be-9c78-43e5-bcaa-a4e0a95f6daa.png)

We should support this in ecl as well.

**Comment by eivindjahren** [comment]
Fixed by https://github.com/equinor/resdata/pull/950
