### ISSUE TITLE
Python wrappers failed to install

### ISSUE THREAD

**Issue by gawilliamsbgs** [equinor/resdata#929]
Good morning, 
I have just built resdata since its rename from ecl. I am using the following cmake string:
**cmake .. -DENABLE_PYTHON=ON -DCMAKE_INSTALL_PREFIX=/data/packages/equinor/resdata/Linux**
This worked fine and build the C code and python wrappers in the previous (ecl) version, but it does not build and install the python wrappers in the current release. The C libraries are fine though! What am I doing wrong?
All the Best and thanks for a great project, Gareth

**Comment by eivindjahren** [comment]
Closing this as the preferred way is to install resdata with pip and the c interface is considered private: https://github.com/equinor/resdata/issues/954
