### ISSUE TITLE
EclSum doesn't read network vectors  

### ISSUE THREAD

**Issue by alifbe** [equinor/resdata#943]
Network vectors from `intersect` are not imported.

This has been resolved in ResInsight in their local copy

https://github.com/OPM/ResInsight/pull/8990

**Comment by eivindjahren** [comment]
The problem is that set_gen_keys does not assign a key to a network var so when you try to look up the var in EclSum by key, then you don't find any network vars.


https://github.com/equinor/ecl/blob/ed744e8b5c28510f41ca021c0318ba0208525e51/lib/ecl/smspec_node.cpp#L663

**Comment by eivindjahren** [comment]
I suggest doing the same fix as they did here:

https://github.com/OPM/ResInsight/blob/47f75b16760d74d2144d107d24d8e5e1da5436c0/ThirdParty/Ert/lib/ecl/smspec_node.cpp#L612

**Comment by andreas-el** [comment]
Alif Be wrote:
I think I figure out the problem. wgname is not defined for network keyword
[12:23](https://equinor.slack.com/archives/D06G22QJEKD/p1707132232260249)
we need to add network to this line https://github.com/equinor/resdata/blob/4062d1e551e087623eb123e5e58f2bcf026db387/lib/resdata/smspec_node.cpp#L567
[smspec_node.cpp](https://github.com/equinor/resdata/blob/4062d1e551e087623eb123e5e58f2bcf026db387/lib/resdata/smspec_node.cpp)
        this->var_type == RD_SMSPEC_LOCAL_WELL_VAR)
<https://github.com/[equinor/resdata](https://github.com/equinor/resdata)|equinor/resdata>equinor/resdata | Added by [GitHub](https://equinor.slack.com/services/B01UGSXJU30)
[12:24](https://equinor.slack.com/archives/D06G22QJEKD/p1707132258521859)
tested on troll dataset and seems to work
