### ISSUE TITLE
writing restart file from scratch

### ISSUE THREAD

**Issue by behzaadh** [equinor/resdata#987]
This is more of a question than an issue. In the README file, you mentioned that it is possible to write the restart file. I generated results from another reservoir simulator, which are in VTK format. Now, I want to import them into Petrel, which means that I have to generate the Eclipse restart file. I wonder if your library supports this functionality. I found the rd_sum_fwrite function, which apparently does the job, but I have not found any tests or examples of how to use this function. It would be great if you could provide some guidance on this matter.

**Comment by eivindjahren** [comment]
Writing a restart file is pretty involved. I would suggest checking out [the opm manual](https://opm-project.org/wp-content/uploads/2023/06/OPM_Flow_Reference_Manual_2023-04_Rev-0_Reduced.pdf) appendix F.

You can build up a `resdata.resfile.FortIO` with `mode=WRITE_MODE` and then use `resdata.resfile.ResdataKW::fwrite` to write the necessary keywords to it.

```python
       import sys
       from resdata.resfile import openFortIO, FortIO, ResdataKW

       restart_content = [ResdataKW("SEQNUM", ...]

       with openFortIO("CASE.UNRST", mode=FortIO.WRITE_MODE) as fortio:
          for kw in restart_content:
                 kw.fwrite(fortio)
```

You can also use a different library called `resfo` see https://resfo.readthedocs.io/en/latest/ , which is a bit more oriented towards manual writing like this.
